name: dprint
on:
  push:
    branches: [main]
  pull_request:

jobs:
  dprint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: dprint/check@v2.2
        with:
          dprint-version: '0.42.5' # selfup { "regex": "\\d[^']+", "script": "dprint --version | cut -d ' ' -f 2" }
